### ISSUE TITLE
Rebuilding the DKMS in Kernel 6.6.2 is problematic

### ISSUE THREAD

**Issue by elhossary** [stefanpartheym/archlinux-ipu6-webcam#57] opened 2023-11-21 13:58 UTC
Hi,
I get these errors while upgrading the Kernel to 6.6.2 / 6.6.3, I am not sure if this is related to the Kernel itself or to the driver. Anyways, the camera still works
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 linux-6.6.3.arch1-1-x86_64                                 128.7 MiB  10.7 MiB/s 00:12 [###################################################] 100%
 thunderbird-115.5.1-1-x86_64                                55.9 MiB  21.2 MiB/s 00:03 [###################################################] 100%
 linux-headers-6.6.3.arch1-1-x86_64                          24.8 MiB  18.5 MiB/s 00:01 [###################################################] 100%
 ripgrep-14.0.3-1-x86_64                                   1508.7 KiB  12.0 MiB/s 00:00 [###################################################] 100%
 liblangtag-0.6.6-1-x86_64                                  329.1 KiB  5.10 MiB/s 00:00 [###################################################] 100%
 Total (5/5)                                                211.2 MiB  12.8 MiB/s 00:17 [###################################################] 100%
(5/5) checking keys in keyring                                                          [###################################################] 100%
(5/5) checking package integrity                                                        [###################################################] 100%
(5/5) loading package files                                                             [###################################################] 100%
(5/5) checking for file conflicts                                                       [###################################################] 100%
(5/5) checking available disk space                                                     [###################################################] 100%
warning: could not get file information for usr/lib/modules/6.6.2-arch1-1/kernel/drivers/media/i2c/hi556.ko.zst
warning: could not get file information for usr/lib/modules/6.6.2-arch1-1/kernel/drivers/media/i2c/ov01a10.ko.zst
warning: could not get file information for usr/lib/modules/6.6.2-arch1-1/kernel/drivers/media/i2c/ov2740.ko.zst
:: Running pre-transaction hooks...
(1/2) Removing linux initcpios...
(2/2) Remove DKMS modules
==> dkms remove --no-depmod ipu6-drivers/r153.067270ff0 -k 6.6.2-arch1-1
==> dkms remove --no-depmod v4l2loopback/r10.cae2954 -k 6.6.2-arch1-1
==> depmod 6.6.2-arch1-1
:: Processing package changes...
(1/5) upgrading liblangtag                                                              [###################################################] 100%
(2/5) upgrading linux                                                                   [###################################################] 100%
(3/5) upgrading linux-headers                                                           [###################################################] 100%
(4/5) upgrading ripgrep                                                                 [###################################################] 100%
(5/5) upgrading thunderbird                                                             [###################################################] 100%
:: Running post-transaction hooks...
(1/6) Arming ConditionNeedsUpdate...
(2/6) Updating module dependencies...
(3/6) Install DKMS modules
==> dkms install --no-depmod xmm7360-pci-git/r231.107b6ba -k 6.6.3-arch1-1
Error! Bad return status for module build on kernel: 6.6.3-arch1-1 (x86_64)
Consult /var/lib/dkms/xmm7360-pci-git/r231.107b6ba/build/make.log for more information.
==> WARNING: `dkms install --no-depmod xmm7360-pci-git/r231.107b6ba -k 6.6.3-arch1-1' exited 10
==> dkms install --no-depmod v4l2loopback/r10.cae2954 -k 6.6.3-arch1-1
==> dkms install --no-depmod ipu6-drivers/r153.067270ff0 -k 6.6.3-arch1-1
==> dkms install --no-depmod ipu6-drivers/0.0.0 -k 6.6.3-arch1-1
Error! Bad return status for module build on kernel: 6.6.3-arch1-1 (x86_64)
Consult /var/lib/dkms/ipu6-drivers/0.0.0/build/make.log for more information.
==> WARNING: `dkms install --no-depmod ipu6-drivers/0.0.0 -k 6.6.3-arch1-1' exited 10
==> depmod 6.6.3-arch1-1
(4/6) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
==> Starting build: '6.6.3-arch1-1'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux.img'
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
==> Starting build: '6.6.3-arch1-1'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux-fallback.img'
==> Image generation successful
(5/6) Updating icon theme caches...
(6/6) Updating the desktop file MIME type cache...
```
and here is the log content
```
cat /var/lib/dkms/ipu6-drivers/0.0.0/build/make.log
DKMS make.log for ipu6-drivers-0.0.0 for kernel 6.6.3-arch1-1 (x86_64)
Tue Nov 21 02:20:10 PM CET 2023
make -C /usr/lib/modules/6.6.3-arch1-1/build M=/var/lib/dkms/ipu6-drivers/0.0.0/build modules
make[1]: Entering directory '/usr/lib/modules/6.6.3-arch1-1/build'
make[3]: *** No rule to make target '/var/lib/dkms/ipu6-drivers/0.0.0/build/drivers/mfd/ljca.o', needed by '/var/lib/dkms/ipu6-drivers/0.0.0/build/ljca.o'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/6.6.3-arch1-1/build/Makefile:1913: /var/lib/dkms/ipu6-drivers/0.0.0/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.6.3-arch1-1/build'
make: *** [Makefile:78: all] Error 2
```

**Comment by stefanpartheym** [comment] 2023-11-22 08:55
Hey @elhossary,

I think, I had the same or a similar issue when I was upgrading to kernel `v6.6.1`.
Will try this on my machine in a few days.

**Comment by iosonofabio** [comment] 2023-11-22 22:55
same here, thanks for taking a look @stefanpartheym

**Comment by stefanpartheym** [comment] 2023-11-24 17:22
Hey @elhossary,

did you upgrade from kernel `v6.5.x` to `v6.6.2`?
I just upgraded from `v6.6.1` to `v6.6.2` and didn't experience any issues regarding the DKMS module.

**Comment by elhossary** [comment] 2023-11-24 17:23
@stefanpartheym no,
from 6.6.1 to 6.6.2

**Comment by GorgetGuilhem** [comment] 2023-11-28 15:58
Same error here upgrading from 6.6.1 to 6.6.2

**Comment by elhossary** [comment] 2023-11-29 14:50
Also, the issue remains when upgrading from 6.6.2 to 6.6.3

**Comment by hinricht** [comment] 2023-11-30 12:01
I also fail with `6.6.2-1-MANJARO`, see this 
[make.log](https://github.com/stefanpartheym/archlinux-ipu6-webcam/files/13512452/make.log) from installing `linux66-headers-6.6.2-1` (Manjaro sway edition). Is this related or should I create a seperate issue for this ?

**Comment by GorgetGuilhem** [comment] 2023-12-11 13:07
Hey, it works again with `6.6.5-arch1-1`.

**Comment by elhossary** [comment] 2023-12-11 13:10
@GorgetGuilhem Thanks, the issue still persists in 6.6.5 for my setup

**Comment by GorgetGuilhem** [comment] 2023-12-11 13:26
@elhossary sorry I updated my previous answer, I did uninstall everything and reinstalled again after kernel upgrade. It may be worth trying for you too !

**Comment by sysmso** [comment] 2023-12-13 13:11
works fine with `6.6.6-2-MANJARO` here. Before upgrading i uninstalled everything, then reinstalled with new kernel.

**Comment by elhossary** [comment] 2024-01-17 14:07
Disappeared in Kernel 6.7.0, but camera does not work though

**Comment by stefanpartheym** [comment] 2024-01-21 13:47
@elhossary Yep, same here. Kernel v6.7.0 breaks a lot of stuff on my Dell XPS 13 Plus 9320, not only the webcam. Had to downgrade to one of the v6.6.x kernel versions.
Uff, this really shit really starting to piss me off at some point... 
Guess we have to patiently wait for fix.

**Comment by elhossary** [comment] 2024-01-21 13:51
I am pissed too, that went too far with breaking things with each release, gotta have some better testing. What I also don't understand is, why it is not working out of the box if they already integrated the drivers in the Kernel.

**Comment by elhossary** [comment] 2024-01-24 09:16
@stefanpartheym 
I got a slightly different output with Kernel 6.7.1, but still does not work

**Comment by stefanpartheym** [comment] 2024-01-24 10:05
@elhossary Thanks for the update. I think I'll have a look at this next week or so.

**Comment by elhossary** [comment] 2024-01-29 11:02
@stefanpartheym 
Still, no luck in 6.7.2. Although, different errors!

**Comment by elhossary** [comment] 2024-03-01 14:53
Well, eventually it works, but the mentioned error are still showing.
I believe that's an issue outside this repo scope. So, yes should be closed

**Comment by stefanpartheym** [comment] 2024-03-01 14:56
Hmm, good point.
Even though, this might be an issue outside of the scope of this repo. I would leave it open, in case someone knows how to get rid of this errors.
Unfortunately, I can't reproduce it on my install though.

**Comment by stefanpartheym** [comment] 2024-10-11 17:33
Ok, closing this one now. :saluting_face:

**Closed by stefanpartheym** 2024-10-11 17:33 UTC
